"""
Robopulse Command Center - Day 3
Async database engine and session factory for the ORM models to use

DATABASE_URL is read from the envirnment variable so that today's demo can point
at a throwaway database for testing purposes without editing our database from yesterday.

Later, we will replace this with a proper .env file and a Pydantic sdettings class in a future demo.
In a real project, you would never commit a password here, it is not secure
"""

import os 

from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.config import settings

"""
Set the database url to an environment variable so that it can be easily changed
without modifying the code and if it is not set, it can fall back on the default
value for dev purposes.
"""
DATABASE_URL= settings.database_url
# os.environ.get(
#     "DATABASE_URL", 
#     # you put your own dtabase url here with your password
#     # EX: postgresql+asyncpg://<yourusername>:<yourpasswod>@localhost:5432/robopulse_dev_2478
#     "postgresql+asyncpg://postgres:Dankness2@localhost:5432/cashcow_dev_2478"
# )

# echo=True enables the logging of all SQL statements generated by SQLAlchemy
engine = create_async_engine(DATABASE_URL, echo=True)

# expire_on_commit=False prevents the session from expiring objecrts after a commit
AsyncSessionLocal = async_sessionmaker(engine, expire_on_commit=False)